- .gitignore
- DEVELOPMENT.md
- Makefile
- pyproject.toml
Resolved some feedback items from the session with Mahdi
- Fixed "```" showing up in markdown
- Switched from jupyter notebook to jupyter lab
- Changed setup instructions slightly to allow user to create their own virtual environment
> Feedback items

- Makefile
- biolearn/load.py
- biolearn/test/data/geo_dnam_test_file
- biolearn/test/test_load.py
Use local file for testing dnam load.
> Optimize tests by using cut down local file

- biolearn/load.py
- biolearn/test/test_load.py
> Fixed the year check on nhanes

- AUTHORS.rst
- biolearn/hematology.py
- doc/changes/names.rst
- doc/index.rst
- doc/modules/clock.rst
- examples/00_epigenetic_biomarkers/plot_epigenetic_clocks_on_geo.py
- Put epigenetic example on tom in main page
- Added contributors
- Fixed for library changes
> Webdoc polish

- biolearn/data/library.yaml
- biolearn/data_library.py
- biolearn/test/test_data_library.py
This adds 6 new data sources bringing us up to 11. Also some slightly improved parsing behavior.
> Add 6 new data sources

- biolearn/dunedin_pace.py
- biolearn/imputation.py
- biolearn/test/test_imputation.py
This adds imputation methods including the method used by DunedinPACE
> Added some imputation methods

- Makefile
- README.rst
- biolearn/imputation.py
- doc/Makefile
- doc/index.rst
- doc/templates/class.rst
- doc/templates/function.rst
- examples/00_epigenetic_biomarkers/plot_epigenetic_clocks_on_geo.py
- pyproject.toml
Updating and simplifying documentation. Improved the performance of imputation with averages.
> Update and simplify documentation

- README.rst
- doc/index.rst
Fixed a link in readme and a formatting issue.
> Some minor doc fixes

- biolearn/clock_gallery.py
- biolearn/dunedin_pace.py
- biolearn/imputation.py
Added Sesame 450k imputation data
sesame 450k hybrid imputation is now the default
Fixed a bug in dunedinPACE imputation
Improved imputation performance in large datasets
> Imputation Work

- LICENSE
- README.rst
- biolearn/imputation.py
- biolearn/model.py
- doc/index.rst
- doc/modules/imputation.rst
- doc/modules/index.rst
- examples/00_epigenetic_biomarkers/plot_custom_imputation_implementation.py
Updates to documentation including 
- A forever discord invite link
- A link to the 2024 biomarkers challenge
- Tiny license fixes
- Updates to imputation documentation
- Working example of custom imputation
> Doc updates. Added imputation example

- biolearn/data/library.yaml
- biolearn/imputation.py
- biolearn/model.py
- biolearn/model_gallery.py
- biolearn/test/test_imputation.py
Fixes averaging imputation to not break on missing cpgs
Fixes GrimAge clock to work when using the model_gallery
Fixes GrimAge clock to implement methylation_sites method
> Fix imputation and gallery

- doc/index.rst
Some fixes for the documentation landing page
> Changed homepage based on feedback

- examples/02_challenge_submissions/README.rst
- examples/02_challenge_submissions/simple_competiton_submission.py
- examples/02_challenge_submissions/training_simple_model.py
Adds examples for creating challenge submissions
> Model examples

- biolearn/model.py
- biolearn/model_gallery.py
Allows for models to specify a default imputation method
> Add default imputation

- README.rst
- doc/index.rst
Add links to the paper to the documentation
> Add link to paper

- biolearn/data/library.yaml
- biolearn/data_library.py
This PR adds two new GEO datasets that have their methylation data in separate supplementatry files. Note that these files will take several minutes to load.
> Added larger GEO datasets

- biolearn/data/library.yaml
- biolearn/data_library.py
Fixes some issues with loading large GEO files. Need to investigate longer term solutions and better testing.
> Fix bugs in loading large geo files

- biolearn/data_library.py
- biolearn/test/test_geodata.py
- pyproject.toml
Adds a helper function for creating a GeoData object from a local methylation matrix dataframe or file.
> Add helper method for loading local file

- examples/02_challenge_submissions/simple_competiton_submission.py
- examples/02_challenge_submissions/training_simple_model.py
Use the new helper method in submission examples
> Updated examples to use helper method to make GeoData

- biolearn/cache.py
- biolearn/data_library.py
- biolearn/defaults.py
- biolearn/model.py
- biolearn/test/test_cache.py
- doc/modules/index.rst
This new cache implementation significantly increases load performance by using pickle and bypassing the slow performance of Pandas parsing large csv files. It also slightly reduces the space usage. Caching can now be configured by the end user setting the size and location of the cache.
Also fixes #60 and #61
> Added new caching mechanism

- doc/modules/cache.rst
> Add missing docs file for caches

- biolearn/data/library.yaml
- biolearn/data_library.py
- pyproject.toml
Adds a new RNA data source which is a composite of two GEO entries
> Add 2 geo rna

- biolearn/data/library.yaml
- biolearn/data_library.py
- biolearn/model.py
- pyproject.toml
Adds the ability to load the challenge data directly using biolearn
Also includes some small fixes
> Added challenge data parser

- biolearn/model.py
#102 
This PR enhances the LinearModel creation by allowing instances to be constructed from an absolute file path or a pandas DataFrame.
> Add support for creating LinearModel from files

- biolearn/model.py
- biolearn/mortality.py
Fix an imputation issue caused by moving the intercept into the model file.
> Fixed issues with imputation caused by moving intercept

- biolearn/load.py
Nhanes changed some file locations. This fixes loading and allows integration tests to pass.
> Fix nhanes loading

- biolearn/load.py
This fixes the issue that appeared with nhanes downloads.
> Nhanes download now supports gzip
